Dataset Preparation and Preprocessing

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Video
from process_videos.helpers.video_to_dataframe import video_to_dataframe

In [2]:
import mediapipe as mp
print(mp.__version__)
print(hasattr(mp, "solutions"))
print(dir(mp))

0.10.14
True
['CalculatorGraph', 'GraphInputStreamAddMode', 'Image', 'ImageFormat', 'ImageFrame', 'Matrix', 'Packet', 'Timestamp', 'ValidatedGraphConfig', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'calculators', 'model_ckpt_util', 'packet_creator', 'packet_getter', 'resource_util', 'solutions', 'tasks']

Load first video

In [3]:
Video("data/videos/arun_swipe_up_down.mp4", embed=True, width=400)

In [4]:
frames = video_to_dataframe("data/videos/arun_swipe_up_down.mp4", flip_image=False)

A:\WS25\ML\final-submission\venv\Lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '

In [5]:
frames

,nose_x,nose_y,nose_z,nose_confidence,left_eye_inner_x,left_eye_inner_y,left_eye_inner_z,left_eye_inner_confidence,left_eye_x,left_eye_y,...,right_heel_z,right_heel_confidence,left_foot_index_x,left_foot_index_y,left_foot_index_z,left_foot_index_confidence,right_foot_index_x,right_foot_index_y,right_foot_index_z,right_foot_index_confidence
0.000000,0.486354,0.263832,-0.416293,0.999914,0.496806,0.239558,-0.399706,0.999775,0.502262,0.240297,...,0.306518,0.008805,0.490941,1.351576,0.256846,0.009532,0.429304,1.351130,0.146675,0.008160
33.333333,0.485038,0.263059,-0.326126,0.999912,0.495935,0.239544,-0.311522,0.999769,0.501607,0.240297,...,0.288335,0.008590,0.489837,1.376554,0.206050,0.009001,0.429312,1.367618,0.137663,0.007805
66.666667,0.484334,0.263080,-0.361249,0.999910,0.495431,0.239548,-0.345692,0.999765,0.501297,0.240301,...,0.333099,0.008706,0.489307,1.378786,0.205990,0.008867,0.429306,1.368508,0.177546,0.007882
100.000000,0.483758,0.262436,-0.368747,0.999909,0.495042,0.239104,-0.352282,0.999767,0.501015,0.239874,...,0.347460,0.009213,0.487624,1.376029,0.214813,0.008966,0.428711,1.367117,0.191547,0.008178
133.333333,0.483587,0.261583,-0.375364,0.999910,0.494771,0.238729,-0.358882,0.999771,0.500831,0.239485,...,0.347102,0.009755,0.486903,1.378954,0.217174,0.008986,0.428133,1.368929,0.190996,0.008467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44966.666667,0.445806,0.197444,-0.537409,0.999737,0.455313,0.169127,-0.519145,0.999455,0.460421,0.169423,...,0.343159,0.055091,0.446341,1.379888,0.228456,0.039017,0.384540,1.374834,0.145666,0.048656
45000.000000,0.445715,0.196351,-0.514400,0.999745,0.455314,0.167922,-0.494314,0.999471,0.460466,0.168163,...,0.349549,0.054654,0.444848,1.383008,0.227837,0.039797,0.382588,1.378611,0.153735,0.048210
45033.333333,0.445670,0.195637,-0.512495,0.999749,0.455312,0.166955,-0.493447,0.999474,0.460491,0.167143,...,0.349958,0.054150,0.444887,1.383294,0.228986,0.039239,0.382651,1.378152,0.160188,0.047291
45066.666667,0.446374,0.195518,-0.511547,0.999757,0.456175,0.166776,-0.491654,0.999493,0.461287,0.166980,...,0.352301,0.055297,0.445666,1.384232,0.195820,0.040281,0.383066,1.378119,0.159876,0.047674
45100.000000,0.446197,0.194427,-0.514246,0.999763,0.456104,0.165864,-0.494650,0.999504,0.461284,0.165946,...,0.350938,0.055264,0.446029,1.386024,0.193884,0.040975,0.383382,1.380704,0.151281,0.047804

In [6]:
frames.index = pd.to_timedelta(frames.index, unit="ms")
frames.index.name = "time"
frames

,nose_x,nose_y,nose_z,nose_confidence,left_eye_inner_x,left_eye_inner_y,left_eye_inner_z,left_eye_inner_confidence,left_eye_x,left_eye_y,...,right_heel_z,right_heel_confidence,left_foot_index_x,left_foot_index_y,left_foot_index_z,left_foot_index_confidence,right_foot_index_x,right_foot_index_y,right_foot_index_z,right_foot_index_confidence
time,,,,,,,,,,,,,,,,,,,,,
0 days 00:00:00,0.486354,0.263832,-0.416293,0.999914,0.496806,0.239558,-0.399706,0.999775,0.502262,0.240297,...,0.306518,0.008805,0.490941,1.351576,0.256846,0.009532,0.429304,1.351130,0.146675,0.008160
0 days 00:00:00.033333333,0.485038,0.263059,-0.326126,0.999912,0.495935,0.239544,-0.311522,0.999769,0.501607,0.240297,...,0.288335,0.008590,0.489837,1.376554,0.206050,0.009001,0.429312,1.367618,0.137663,0.007805
0 days 00:00:00.066666667,0.484334,0.263080,-0.361249,0.999910,0.495431,0.239548,-0.345692,0.999765,0.501297,0.240301,...,0.333099,0.008706,0.489307,1.378786,0.205990,0.008867,0.429306,1.368508,0.177546,0.007882
0 days 00:00:00.100000,0.483758,0.262436,-0.368747,0.999909,0.495042,0.239104,-0.352282,0.999767,0.501015,0.239874,...,0.347460,0.009213,0.487624,1.376029,0.214813,0.008966,0.428711,1.367117,0.191547,0.008178
0 days 00:00:00.133333333,0.483587,0.261583,-0.375364,0.999910,0.494771,0.238729,-0.358882,0.999771,0.500831,0.239485,...,0.347102,0.009755,0.486903,1.378954,0.217174,0.008986,0.428133,1.368929,0.190996,0.008467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0 days 00:00:44.966666667,0.445806,0.197444,-0.537409,0.999737,0.455313,0.169127,-0.519145,0.999455,0.460421,0.169423,...,0.343159,0.055091,0.446341,1.379888,0.228456,0.039017,0.384540,1.374834,0.145666,0.048656
0 days 00:00:45,0.445715,0.196351,-0.514400,0.999745,0.455314,0.167922,-0.494314,0.999471,0.460466,0.168163,...,0.349549,0.054654,0.444848,1.383008,0.227837,0.039797,0.382588,1.378611,0.153735,0.048210
0 days 00:00:45.033333333,0.445670,0.195637,-0.512495,0.999749,0.455312,0.166955,-0.493447,0.999474,0.460491,0.167143,...,0.349958,0.054150,0.444887,1.383294,0.228986,0.039239,0.382651,1.378152,0.160188,0.047291
0 days 00:00:45.066666667,0.446374,0.195518,-0.511547,0.999757,0.456175,0.166776,-0.491654,0.999493,0.461287,0.166980,...,0.352301,0.055297,0.445666,1.384232,0.195820,0.040281,0.383066,1.378119,0.159876,0.047674
0 days 00:00:45.100000,0.446197,0.194427,-0.514246,0.999763,0.456104,0.165864,-0.494650,0.999504,0.461284,0.165946,...,0.350938,0.055264,0.446029,1.386024,0.193884,0.040975,0.383382,1.380704,0.151281,0.047804

In [7]:
 # coordinates for left elbow:
frames[["left_wrist_y", "right_wrist_y"]]

                           left_wrist_y  right_wrist_y
time
0 days 00:00:00                0.833973       0.832635
0 days 00:00:00.033333333      0.834464       0.831509
0 days 00:00:00.066666667      0.835064       0.829135
0 days 00:00:00.100000         0.835218       0.826495
0 days 00:00:00.133333333      0.835343       0.825468
...                                 ...            ...
0 days 00:00:44.966666667      0.782297       0.773493
0 days 00:00:45                0.782363       0.774000
0 days 00:00:45.033333333      0.782372       0.774607
0 days 00:00:45.066666667      0.782346       0.774592
0 days 00:00:45.100000         0.782271       0.774591

[1354 rows x 2 columns]

In [8]:
# select frames between 3rd and 4th second
start = pd.to_timedelta(3, unit="s")
stop = pd.to_timedelta(4, unit="s")
frames.loc[(frames.index >= start) & (frames.index < stop)]

,nose_x,nose_y,nose_z,nose_confidence,left_eye_inner_x,left_eye_inner_y,left_eye_inner_z,left_eye_inner_confidence,left_eye_x,left_eye_y,...,right_heel_z,right_heel_confidence,left_foot_index_x,left_foot_index_y,left_foot_index_z,left_foot_index_confidence,right_foot_index_x,right_foot_index_y,right_foot_index_z,right_foot_index_confidence
time,,,,,,,,,,,,,,,,,,,,,
0 days 00:00:03,0.484881,0.252985,-0.355402,0.999941,0.494529,0.223626,-0.334301,0.999853,0.500265,0.223502,...,0.532961,0.028722,0.470880,1.380706,0.247537,0.015702,0.419317,1.355986,0.360693,0.013831
0 days 00:00:03.033333333,0.484619,0.252812,-0.335808,0.999938,0.494337,0.223607,-0.311270,0.999844,0.500023,0.223492,...,0.554326,0.026375,0.471587,1.384391,0.250583,0.014228,0.419675,1.359925,0.383221,0.012599
0 days 00:00:03.066666667,0.484119,0.254089,-0.334179,0.999930,0.493558,0.225265,-0.310036,0.999823,0.499069,0.225091,...,0.543728,0.024387,0.473388,1.384090,0.254230,0.012946,0.422612,1.360573,0.374076,0.011539
0 days 00:00:03.100000,0.482268,0.248253,-0.317551,0.999922,0.492056,0.222890,-0.293933,0.999799,0.497763,0.223075,...,0.523563,0.022716,0.473631,1.383730,0.249308,0.011800,0.423961,1.360153,0.362471,0.010591
0 days 00:00:03.133333333,0.476862,0.244503,-0.316804,0.999913,0.488695,0.221264,-0.295277,0.999774,0.494586,0.221939,...,0.533714,0.021572,0.473906,1.374379,0.247175,0.010877,0.424605,1.351926,0.384350,0.009829
0 days 00:00:03.166666667,0.475675,0.236011,-0.302751,0.999896,0.487882,0.215919,-0.280811,0.999729,0.493859,0.217001,...,0.522281,0.020579,0.475068,1.367349,0.234077,0.010088,0.426021,1.347113,0.374721,0.009160
0 days 00:00:03.200000,0.476149,0.232588,-0.292249,0.999874,0.487917,0.213655,-0.270789,0.999673,0.493952,0.214983,...,0.520723,0.019635,0.475359,1.360042,0.232140,0.009398,0.426194,1.338812,0.380422,0.008545
0 days 00:00:03.233333333,0.476223,0.232373,-0.304632,0.999862,0.488430,0.213335,-0.282809,0.999643,0.494323,0.214793,...,0.534988,0.018799,0.477051,1.358678,0.236780,0.008826,0.427085,1.338050,0.390830,0.008037
0 days 00:00:03.266666667,0.476454,0.230999,-0.300537,0.999856,0.488747,0.212351,-0.277856,0.999629,0.494581,0.214022,...,0.533680,0.017916,0.477662,1.357955,0.261453,0.008231,0.427430,1.337027,0.390657,0.007515
0 days 00:00:03.300000,0.475640,0.231214,-0.302812,0.999839,0.488298,0.212379,-0.279775,0.999587,0.494135,0.214078,...,0.545246,0.017103,0.477745,1.353125,0.288015,0.007702,0.427946,1.330397,0.403462,0.007036
0 days 00:00:03.333333333,0.474750,0.233863,-0.328227,0.999829,0.487184,0.214232,-0.304967,0.999565,0.492915,0.215924,...,0.581811,0.016625,0.478352,1.350435,0.294451,0.007341,0.428676,1.327239,0.429580,0.006726
0 days 00:00:03.366666667,0.473718,0.235237,-0.333017,0.999825,0.485991,0.215539,-0.309671,0.999554,0.491699,0.217273,...,0.583349,0.016148,0.478360,1.351084,0.284447,0.006915,0.428984,1.328193,0.431449,0.006375
0 days 00:00:03.400000,0.474002,0.236476,-0.328355,0.999810,0.486087,0.216663,-0.304900,0.999511,0.491738,0.218396,...,0.566372,0.015788,0.478259,1.351123,0.282728,0.006592,0.429039,1.328983,0.415927,0.006072
0 days 00:00:03.433333333,0.473495,0.237495,-0.334140,0.999800,0.485604,0.217500,-0.311652,0.999493,0.491270,0.219250,...,0.585310,0.015644,0.478484,1.348300,0.279955,0.006470,0.429077,1.324119,0.436582,0.005932
0 days 00:00:03.466666667,0.473401,0.237616,-0.333080,0.999793,0.485591,0.217660,-0.310747,0.999478,0.491280,0.219455,...,0.579096,0.015225,0.478423,1.348962,0.256781,0.006154,0.429047,1.325172,0.429538,0.005662
0 days 00:00:03.500000,0.476053,0.238005,-0.332434,0.999792,0.487713,0.218048,-0.310376,0.999477,0.493287,0.219886,...,0.573414,0.014764,0.477304,1.352727,0.245785,0.005801,0.428265,1.327733,0.422587,0.005382
0 days 00:00:03.533333333,0.481022,0.238627,-0.319868,0.999788,0.491160,0.218273,-0.296632,0.999470,0.496284,0.220071,...,0.571336,0.014264,0.475770,1.357429,0.234148,0.005468,0.427261,1.330869,0.421479,0.005104
0 days 00:00:03.566666667,0.484011,0.240761,-0.319375,0.999788,0.493509,0.219470,-0.295480,0.999474,0.498318,0.221175,...,0.568755,0.013963,0.474774,1.359496,0.238393,0.005207,0.426424,1.333258,0.412949,0.004926
0 days 00:00:03.600000,0.483761,0.241645,-0.313533,0.999788,0.492735,0.219725,-0.290751,0.999472,0.497448,0.221368,...,0.556896,0.013411,0.470898,1.363020,0.211783,0.004863,0.423931,1.336644,0.409450,0.004646
0 days 00:00:03.633333333,0.485583,0.242346,-0.307002,0.999793,0.493703,0.219924,-0.283252,0.999489,0.498280,0.221480,...,0.517878,0.013417,0.470536,1.362564,0.200599,0.004748,0.423085,1.336299,0.369856,0.004538
0 days 00:00:03.666666667,0.485879,0.243171,-0.305741,0.999797,0.494038,0.220192,-0.281806,0.999502,0.498669,0.221663,...,0.518131,0.012920,0.469889,1.365558,0.207679,0.004457,0.422006,1.339000,0.374655,0.004271
0 days 00:00:03.700000,0.485795,0.244401,-0.306797,0.999805,0.493987,0.220776,-0.283391,0.999526,0.498658,0.222029,...,0.492468,0.013226,0.468588,1.363360,0.190765,0.004357,0.421077,1.337838,0.345425,0.004187
0 days 00:00:03.733333333,0.485450,0.246364,-0.308157,0.999813,0.492917,0.221945,-0.284907,0.999547,0.497553,0.222920,...,0.497842,0.012982,0.468860,1.371511,0.161701,0.004119,0.421229,1.349119,0.339968,0.004024
0 days 00:00:03.766666667,0.484147,0.248218,-0.320669,0.999818,0.491747,0.223306,-0.298256,0.999560,0.496219,0.224177,...,0.521464,0.013157,0.468951,1.371624,0.142551,0.004021,0.420885,1.350062,0.348117,0.004014
0 days 00:00:03.800000,0.480280,0.252487,-0.332303,0.999800,0.489137,0.226088,-0.311250,0.999523,0.493515,0.226686,...,0.536465,0.013906,0.469084,1.361337,0.168646,0.004351,0.420600,1.341578,0.369682,0.004275
0 days 00:00:03.833333333,0.478585,0.252257,-0.336563,0.999780,0.487926,0.226240,-0.315244,0.999476,0.492278,0.226927,...,0.591892,0.014277,0.469390,1.361373,0.150532,0.004525,0.420559,1.342315,0.423637,0.004479
0 days 00:00:03.866666667,0.473925,0.251682,-0.334019,0.999733,0.483829,0.225648,-0.312231,0.999359,0.488151,0.226368,...,0.598215,0.014469,0.469485,1.362603,0.149977,0.004510,0.420047,1.344293,0.432024,0.004563
0 days 00:00:03.900000,0.463410,0.256371,-0.331504,0.999681,0.477012,0.228393,-0.311623,0.999241,0.481768,0.229042,...,0.587086,0.015010,0.468724,1.359233,0.157985,0.004641,0.418979,1.339965,0.430537,0.004697
0 days 00:00:03.933333333,0.454027,0.254913,-0.246073,0.999637,0.467347,0.223644,-0.247867,0.999125,0.471432,0.223925,...,0.560670,0.015250,0.463819,1.354650,0.164793,0.004479,0.415681,1.331316,0.423359,0.004604
0 days 00:00:03.966666667,0.456107,0.248427,-0.268482,0.999628,0.468940,0.218620,-0.263121,0.999100,0.473297,0.219415,...,0.563140,0.015346,0.463381,1.354743,0.122320,0.004258,0.415861,1.331607,0.429646,0.004488

In [9]:
ELAN_ANNOTATION_FILE_PATH = "data/elan_data/text_files/arun_swipe_up_down.txt"
# read the ELAN file as CSV; only read the relevant columns (specified by `usecols`)
annotations = pd.read_csv(ELAN_ANNOTATION_FILE_PATH, sep="\t", header=None, usecols=[3, 5, 8], names=["start", "end", "label"])

# convert start and end timestamps into a datetime-datatype – this is important for the next step
annotations["start"] = pd.to_timedelta(annotations["start"], unit="s")
annotations["end"]   = pd.to_timedelta(annotations["end"], unit="s")

annotations

                    start                    end       label
0  0 days 00:00:02.330000 0 days 00:00:03.330000    swipe_up
1  0 days 00:00:03.833000 0 days 00:00:04.833000  swipe_down
2  0 days 00:00:07.485000 0 days 00:00:08.485000    swipe_up
3  0 days 00:00:12.272000 0 days 00:00:13.272000  swipe_down
4  0 days 00:00:15.960000 0 days 00:00:16.950000    swipe_up
5  0 days 00:00:21.160000 0 days 00:00:22.400000  swipe_down
6  0 days 00:00:25.080000 0 days 00:00:26.066000    swipe_up
7  0 days 00:00:26.440000 0 days 00:00:27.480000  swipe_down
8  0 days 00:00:31.480000 0 days 00:00:32.413000    swipe_up
9  0 days 00:00:32.760000 0 days 00:00:33.920000  swipe_down
10 0 days 00:00:37.560000 0 days 00:00:38.520000    swipe_up
11 0 days 00:00:42.922000 0 days 00:00:44.070000  swipe_down

In [10]:
# the default label will be 'idle'
frames["ground_truth"] = "idle"

# iterate over each entry from the ELAN file, select the corresponding frames and label them accordingly:
for idx, ann in annotations.iterrows():
    annotated_frames = (frames.index >= ann["start"]) & (frames.index <= ann["end"])
    frames.loc[annotated_frames, "ground_truth"] = ann["label"]

frames[["left_wrist_y", "right_wrist_y", "ground_truth"]]

                           left_wrist_y  right_wrist_y ground_truth
time
0 days 00:00:00                0.833973       0.832635         idle
0 days 00:00:00.033333333      0.834464       0.831509         idle
0 days 00:00:00.066666667      0.835064       0.829135         idle
0 days 00:00:00.100000         0.835218       0.826495         idle
0 days 00:00:00.133333333      0.835343       0.825468         idle
...                                 ...            ...          ...
0 days 00:00:44.966666667      0.782297       0.773493         idle
0 days 00:00:45                0.782363       0.774000         idle
0 days 00:00:45.033333333      0.782372       0.774607         idle
0 days 00:00:45.066666667      0.782346       0.774592         idle
0 days 00:00:45.100000         0.782271       0.774591         idle

[1354 rows x 3 columns]

In [12]:
from pathlib import Path

# Create output directory if it doesn't exist
output_dir = Path("data/csv_results")
output_dir.mkdir(parents=True, exist_ok=True)

save_frames = frames.copy()

# convert index back to integers so it looks nicer in CSV
save_frames.index = save_frames.index.astype("int64") // 1_000_000

# save all data with the new ground_truth column
save_frames.to_csv(
    output_dir / "arun_swipe_up_poses.csv",
    index=True
)

# save only the ground_truth column
save_frames["ground_truth"].to_csv(
    output_dir / "arun_swipe_up_ground_truth.csv",
    index=True
)